project:
  type: website

website:
  title: "College Class Portfolio"
  site-url: "https://goldmeer.github.io/college_class_portfolio"
  repo-url: "https://github.com/Goldmeer/college_class_portfolio"

  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - text: "Classes"
        menu:
          - href: classes/linear-algebra.qmd
            text: "Linear Algebra"
          - href: classes/multivariable-calculus.qmd
            text: "Multivariable Calculus"

format:
  html:
    theme: cosmo
    toc: true
